### ISSUE TITLE
ITM Slaves! moved to Pleroma 

### ISSUE THREAD

**Issue by MvB1985** [bit-badger/jobs-jobs-jobs#33] opened 2022-07-04 11:13 UTC
I have an mastedon account and a ITM account, but when i try to log in the site is says 
a-mails adress or password invalid.

how can i solve this?

**Comment by danieljsummers** [comment] 2022-07-04 22:15
I believe the issue is with the ITM site; I just tried to log on there and got the same result. I'll reach out to the site operator and see if they are aware of any issues.

**Comment by danieljsummers** [comment] 2022-07-04 23:53
The ITM Slaves! instance changed from Mastodon to Pleroma, but they were not able to migrate accounts. You should be able to create a new account with your previous credentials. However, it looks like the API integration has changed. I'm going to use this issue to track fixing it. Thank you for reporting the issue!

**Comment by MvB1985** [comment] 2022-07-05 09:14
Thank you for your response, 
i tried to log in again, but is still says 

Invalid Username/Password

mark1985
@mark1985@itmslaves.com


do i have to do someting else?

**Comment by johnwtrain** [comment] 2022-07-05 15:29
> Thank you for your response, i tried to log in again, but is still says
> 
> Invalid Username/Password
> 
> mark1985 @[mark1985@itmslaves.com](mailto:mark1985@itmslaves.com)
> 
> do i have to do someting else?

Howdy, admin of ITM Slaves here. You'll have to create a new account to use the site. When we switched to Pleroma from Mastodon earlier this year I was not able to migrate the existing users. Sorry for the inconvenience! Pleroma has been working really well so you won't have to do this again.

**Comment by danieljsummers** [comment] 2022-07-05 16:04
Also, even once you do that, the attempt to log on to Jobs, Jobs, Jobs will give you the same error; that's what I need to fix (once I figure out how Pleroma does that).

**Comment by danieljsummers** [comment] 2022-07-12 02:27
For version 2.2.2, the ITM, Slaves! button is disabled, with a note that the integration is broken. Hopefully I'll be able to figure it out shortly!

**Comment by johnwtrain** [comment] 2022-07-12 12:26
> 

Let me know if I can be of any assistance!

**Comment by danieljsummers** [comment] 2022-07-12 13:18
In my initial research, it looks like Pleroma supports the [same API as Mastodon](https://docs-develop.pleroma.social/backend/development/API/differences_in_mastoapi_responses/) (with a few noted exceptions*). I think the main issue comes down to the client ID and secret being unknown to the new server. On Mastodon, I got that by editing my profile, then clicking "Development". There, I could register an application, declare what scopes it needs, etc., and it generated the client ID and secret there. This is what I can't find on Pleroma.

If you can see something like that in the admin area, let me know, and I'll send you the details for the application (but not publicly - LOL).

\* None of the exceptions apply to this application. Jobs, Jobs, Jobs uses exactly 2 API calls; one [verifies that the user has allowed the application](https://github.com/bit-badger/jobs-jobs-jobs/blob/323ea8359481c5479c706b79cb43a4716db702a7/src/JobsJobsJobs/Server/Auth.fs#L44) to access their profile (which also verifies that they have a valid account), and the other [retrieves the user's basic account details](https://github.com/bit-badger/jobs-jobs-jobs/blob/323ea8359481c5479c706b79cb43a4716db702a7/src/JobsJobsJobs/Server/Auth.fs#L61) so we can display names and handles. It's an intentionally minimal implementation.

**Comment by johnwtrain** [comment] 2022-07-12 22:17
> In my initial research, it looks like Pleroma supports the [same API as Mastodon](https://docs-develop.pleroma.social/backend/development/API/differences_in_mastoapi_responses/) (with a few noted exceptions*). I think the main issue comes down to the client ID and secret being unknown to the new server. On Mastodon, I got that by editing my profile, then clicking "Development". There, I could register an application, declare what scopes it needs, etc., and it generated the client ID and secret there. This is what I can't find on Pleroma.
> 
> If you can see something like that in the admin area, let me know, and I'll send you the details for the application (but not publicly - LOL).
> 
> * None of the exceptions apply to this application. Jobs, Jobs, Jobs uses exactly 2 API calls; one [verifies that the user has allowed the application](https://github.com/bit-badger/jobs-jobs-jobs/blob/323ea8359481c5479c706b79cb43a4716db702a7/src/JobsJobsJobs/Server/Auth.fs#L44) to access their profile (which also verifies that they have a valid account), and the other [retrieves the user's basic account details](https://github.com/bit-badger/jobs-jobs-jobs/blob/323ea8359481c5479c706b79cb43a4716db702a7/src/JobsJobsJobs/Server/Auth.fs#L61) so we can display names and handles. It's an intentionally minimal implementation.
![Capture](https://user-images.githubusercontent.com/108748730/178604984-a386a8a4-9b1c-4816-a87b-9467a518cab4.PNG)

Found this, relevant?

**Comment by danieljsummers** [comment] 2022-07-16 19:13
_(sorry for the delay)_

It looks like those are overall settings for how OAuth requests are handled, not for defining specific applications / consumers.

**Comment by danieljsummers** [comment] 2022-07-17 20:59
@johnwtrain I wouldn't spend a whole lot more time on this. _(story time ahead)_

When I first conceived of this site, tying login to No Agenda Social accounts seemed to be a great way to make this site "by NA for NA". With registration at NAS closed off, I ended up opening it up to ITM Slaves! and Liberty Woof - but I declined from Podcast Index Social, as that's much wider than No Agenda. What I was trying to do was walk the line where people could drop some of the anonymity of their NAS handle (if they wanted), but know that only other members would be able to see it.

That hasn't been how it's worked out, though. Uptake has been light, and I've never seen a person share either a job listing or an employment profile on NAS (though, admittedly, I don't have time to crawl the Local timeline all the time). I discussed this a bit with Adam, and he mentioned that it might work better if they pitched it during the show more than just in passing, as has happened a couple of times. I think they did it once, but that didn't really move the needle either.

It's my understanding that the art generator, the meet-up site, etc. are all sites where anyone can sign up and participate; and, to my knowledge, they don't have issues with other people showing up and causing problems. I've been leaning toward moving that way with this site, and this difficulty may just be the final indicator that I should go that way. I'd want to make sure people were able to preserve their existing profiles once they create an account, but I may just do a manual mapping for folks there.

There are 18 users of ITM Slaves! registered, 3 of whom have employment profiles, and no job listings.

At any rate, if you've found the right combination, I'm happy to fix what's there; otherwise, I may defer to a v3 that uses its own authentication. I've used Auth0 on other projects, and it's nice because you can accept other logins through them, as well as do your own username/password if you want. Also, let me know what you think about that plan. I have another project I'm working to get to release-candidate status, so I won't be jumping on this right away - I still have lots of time to ponder.

**Comment by danieljsummers** [comment] 2022-08-22 02:21
Version 3 will not be dependent on external Fediverse servers, and I'm beginning work on it. I'm closing this particular issue out, but stay tuned on NAS and ITM, Slaves! for v3 release information.

**Closed by danieljsummers** 2022-08-22 02:21 UTC

**Comment by johnwtrain** [comment] 2022-08-22 12:04
> Version 3 will not be dependent on external Fediverse servers, and I'm beginning work on it. I'm closing this particular issue out, but stay tuned on NAS and ITM, Slaves! for v3 release information.

Daniel,

Everyone on ITM Slaves has moved over to NAS now that registration is open for a bunch of new people. We'll be shutting down at the end of the month so you don't have to work on supporting Soapbox at this time. Cheers! John.
